name: AlleBilderAnzeigen

on:
  push:
    branches: [ main ]
env:
    PROJECT_PATH: PlcDigitalTwinAutoTest/AlleBilderAnzeigen/AlleBilderAnzeigen.csproj
      
jobs:
  deploy:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o PublishMin

    - uses: actions/upload-artifact@v3
      with:
        name: AlleBilderAnzeigen Min
        path: PublishMin
