name: AlleBilderAnzeigen

on:
  push:
    branches: [ main ]
env:
    PROJECT_PATH: PlcDigitalTwinAutoTest/AlleBilderAnzeigen/AlleBilderAnzeigen.csproj
      
jobs:
  deploy:
    runs-on: windows-latest 

    steps:
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
          timeZone: 1
          format: 'YYYY-MM-DD-HH-mm-ss'

    - name: Usage
      env:
          NAME: AlleBilderAnzeigen
          TIME: "${{ steps.time.outputs.time }}"
      run: |
          echo $${{ env.NAME }}
          echo $${{ env.TIME }}
          echo $NAME
          echo $TIME

    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o PublishMin

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.NAME }}-${{ env.TIME }}
        path: PublishMin
