name: AlleBilderAnzeigen

on:
  push:
    branches: [ main ]

  label: 
    uses: nanzm/get-time-action@v1.1
    with:
          timeZone: 0
          format: 'YYYY-MM-DD-HH-mm-ss'

env:
      PROJECT_PATH: PlcDigitalTwinAutoTest/AlleBilderAnzeigen/AlleBilderAnzeigen.csproj
      TIME: "${{ steps.time.outputs.time }}"
jobs:
  deploy:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o PublishMin

    - uses: actions/upload-artifact@v2
      with:
        name: AlleBilderAnzeigen ${{ env.TIME }}
        path: PublishMin
