name: Path Lister
on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      Solution_Name: PlcDigitalTwinAutoTest.sln
      Test_Project_Path: PlcDigitalTwinAutoTest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch action
      id: pl
      uses: Rishabh510/Path-lister-action@master
      with:
          path: "."
          type: "*"

    - name: Output results
      run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
